development:
  adapter: postgresql
  encoding: utf8
  database: clientes
  username: postgres
  password: eFHoMI8jklBc8gHrXrS8
  host: containers-us-west-178.railway.app

test:
  adapter: postgresql
  encoding: utf8
  database: clientes
  username: postgres
  password: eFHoMI8jklBc8gHrXrS8
  host: containers-us-west-178.railway.app

production:
  adapter: postgresql
  encoding: utf8
  database: clientes
  username: postgres
  password: eFHoMI8jklBc8gHrXrS8
  host: containers-us-west-178.railway.app
