development:
  adapter: postgresql
  encoding: utf8
  database: railway
  username: postgres
  password: vJmeVu9vjNPyb8eJJzn1
  host: containers-us-west-136.railway.app

test:
  adapter: postgresql
  encoding: utf8
  database: railway
  username: postgres
  password: vJmeVu9vjNPyb8eJJzn1
  host: containers-us-west-136.railway.app

production:
  adapter: postgresql
  encoding: utf8
  database: railway
  username: postgres
  password: vJmeVu9vjNPyb8eJJzn1
  host: containers-us-west-136.railway.app
